version: "3.8"

services:
  django:
    build: ./elasticsearchapi
    container_name: django_app
    volumes:
      - ./elasticsearchapi:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_started
      esearch:
        condition: service_healthy
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  esearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.5
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://esearch:9200 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: always

  # Optional Kibana UI for Elasticsearch management
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:9.1.5
  #   container_name: kibana
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     esearch:
  #       condition: service_healthy
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://esearch:9200
  #   restart: always

volumes:
  postgres_data:
  es_data:
